---
- name: get hosted zone from hostname
  set_fact: cHostedZone="{{ '.'.join(inventory_hostname.split('.')[-3:]) }}."
  delegate_to: localhost
  tags:
    - dns

- name: create a new DNS entry at Route53
  route53:
    aws_access_key: "{{ lookup('file', '/etc/ssl/keys/aws_route53/aws_access_key_route53.key') }}"
    aws_secret_key: "{{ lookup('file', '/etc/ssl/keys/aws_route53/aws_secret_key_route53.key') }}"
    record: "{{ inventory_hostname }}"
    zone: "{{ cHostedZone }}"
    state: create
    type: A
    ttl: 7200
    value: "{{ ipaddr }}"
  delegate_to: localhost
  tags:
    - dns