---
- name: open firewall
  command: "iptables -P {{ item }} ACCEPT"
  with_items:
    - INPUT
    - OUTPUT
    - FORWARD
  become: yes
  tags:
    - stop_arno

- name: stop arno-iptables
  command: /etc/init.d/arno-iptables-firewall stop
  become: yes
  tags:
    - stop_arno

